import ast_nodes as ast

BUILTINS = {
    'SUBSTR': '_pli_substr',
    'INDEX': '_pli_index',
    'LENGTH': '_pli_length',
    'VERIFY': '_pli_verify',
    'TRANSLATE': '_pli_translate',
    'TRIM': '_pli_trim',
    'MOD': '_pli_mod',
    'ABS': '_pli_abs',
    'MAX': '_pli_max',
    'MIN': '_pli_min',
    'SQRT': '_pli_sqrt',
    'ROUND': '_pli_round',
    'CEIL': '_pli_ceil',
    'FLOOR': '_pli_floor',
    'SIGN': '_pli_sign',
    'DATE': '_pli_date',
    'TIME': '_pli_time',
}

def pli_name(name: str) -> str:
    n = name.upper()
    if n in BUILTINS:
        return BUILTINS[n]
    return f"pli_{name.lower()}"

class CodeGenerator:
    def __init__(self):
        self.indent_level = 0
        self.lines = []
        self.temp_counter = 0
        self.param_stack = []

    def get_temp(self, prefix="_t") -> str:
        self.temp_counter += 1
        return f"{prefix}{self.temp_counter}"

    def emit(self, line: str = ""):
        if line.strip():
            self.lines.append("    " * self.indent_level + line)
        else:
            self.lines.append("")

    def indent(self):
        self.indent_level += 1

    def dedent(self):
        self.indent_level = max(0, self.indent_level - 1)

    def generate(self, program: ast.Program, standalone: bool = True) -> str:
        self.lines = []
        self.indent_level = 0
        self.param_stack = []

        if standalone:
            self.emit("#!/usr/bin/env python3")
            self.emit("# Generated by PLIC - PL/I Compiler")
            self.emit("import sys")
            self.emit("import math")
            self.emit("import datetime")
            self.emit("")
            with open("/plic/runtime.py", "r") as f:
                runtime_code = f.read()
            self.lines.append(runtime_code)
            self.emit("")

        main_proc = None
        for proc in program.procedures:
            if proc.is_main:
                main_proc = proc
            self.gen_procedure(proc)
            self.emit("")

        if main_proc:
            self.emit("if __name__ == '__main__':")
            self.indent()
            self.emit(f"{pli_name(main_proc.name)}()")
            self.dedent()
        elif program.procedures:
            self.emit("if __name__ == '__main__':")
            self.indent()
            self.emit(f"{pli_name(program.procedures[0].name)}()")
            self.dedent()

        return "\n".join(self.lines)

    def gen_procedure(self, proc: ast.ProcedureDecl):
        params = [pli_name(p) for p in proc.params]
        self.param_stack.append(set(p.upper() for p in proc.params))

        self.emit(f"def {pli_name(proc.name)}({', '.join(params)}):")
        self.indent()

        if not proc.body:
            self.emit("pass")
            self.dedent()
            self.param_stack.pop()
            return

        for stmt in proc.body:
            self.gen_stmt(stmt)

        self.dedent()
        self.param_stack.pop()

    def is_current_param(self, name: str) -> bool:
        if self.param_stack:
            return name.upper() in self.param_stack[-1]
        return False

    def gen_stmt(self, stmt: ast.Stmt):
        if isinstance(stmt, ast.DeclareStmt):
            for decl in stmt.decls:
                var = pli_name(decl.name)
                if self.is_current_param(decl.name):
                    continue

                if decl.bounds:
                    bounds_repr = repr(decl.bounds)
                    default_val = "0"
                    if "FLOAT" in decl.data_type: default_val = "0.0"
                    elif "CHAR" in decl.data_type: default_val = "''"
                    self.emit(f"{var} = PliArray({bounds_repr}, default={default_val})")
                elif decl.init is not None:
                    init_expr = self.gen_expr(decl.init)
                    self.emit(f"{var} = {init_expr}")
                else:
                    if "FLOAT" in decl.data_type:
                        self.emit(f"{var} = 0.0")
                    elif "CHAR" in decl.data_type:
                        self.emit(f"{var} = ''")
                    elif "BIT" in decl.data_type:
                        self.emit(f"{var} = ''")
                    else:
                        self.emit(f"{var} = 0")

        elif isinstance(stmt, ast.AssignStmt):
            if isinstance(stmt.target, ast.VarExpr):
                val = self.gen_expr(stmt.expr)
                self.emit(f"{pli_name(stmt.target.name)} = {val}")
            elif isinstance(stmt.target, ast.CallOrIndexExpr):
                indices = [self.gen_expr(arg) for arg in stmt.target.args]
                val = self.gen_expr(stmt.expr)
                arr_name = pli_name(stmt.target.callee)
                if len(indices) == 1:
                    self.emit(f"{arr_name}[{indices[0]}] = {val}")
                else:
                    self.emit(f"{arr_name}[({', '.join(indices)})] = {val}")
            elif isinstance(stmt.target, ast.SubstrExpr):
                val = self.gen_expr(stmt.expr)
                target_name = pli_name(stmt.target.target.name)
                start = self.gen_expr(stmt.target.start)
                length = self.gen_expr(stmt.target.length) if stmt.target.length else "None"
                self.emit(f"{target_name} = _pli_set_substr({target_name}, {start}, {length}, {val})")

        elif isinstance(stmt, ast.IfStmt):
            cond = self.gen_expr(stmt.condition)
            self.emit(f"if {cond}:")
            self.indent()
            if stmt.then_branch:
                for s in stmt.then_branch:
                    self.gen_stmt(s)
            else:
                self.emit("pass")
            self.dedent()
            if stmt.else_branch:
                self.emit("else:")
                self.indent()
                for s in stmt.else_branch:
                    self.gen_stmt(s)
                self.dedent()

        elif isinstance(stmt, ast.DoGroupStmt):
            if stmt.body:
                for s in stmt.body:
                    self.gen_stmt(s)
            else:
                self.emit("pass")

        elif isinstance(stmt, ast.DoWhileStmt):
            cond = self.gen_expr(stmt.condition)
            self.emit(f"while {cond}:")
            self.indent()
            if stmt.body:
                for s in stmt.body:
                    self.gen_stmt(s)
            else:
                self.emit("pass")
            self.dedent()

        elif isinstance(stmt, ast.DoUntilStmt):
            self.emit("while True:")
            self.indent()
            if stmt.body:
                for s in stmt.body:
                    self.gen_stmt(s)
            cond = self.gen_expr(stmt.condition)
            self.emit(f"if {cond}: break")
            self.dedent()

        elif isinstance(stmt, ast.DoIterativeStmt):
            vname = pli_name(stmt.var_name)
            t_step = self.get_temp("_step")
            t_to = self.get_temp("_to")
            start_val = self.gen_expr(stmt.start)
            to_val = self.gen_expr(stmt.to)
            step_val = self.gen_expr(stmt.by) if stmt.by else "1"

            self.emit(f"{vname} = {start_val}")
            self.emit(f"{t_step} = {step_val}")
            self.emit(f"{t_to} = {to_val}")
            self.emit(f"while ({t_step} >= 0 and {vname} <= {t_to}) or ({t_step} < 0 and {vname} >= {t_to}):")
            self.indent()

            if stmt.while_cond:
                wc = self.gen_expr(stmt.while_cond)
                self.emit(f"if not ({wc}): break")

            if stmt.body:
                for s in stmt.body:
                    self.gen_stmt(s)

            if stmt.until_cond:
                uc = self.gen_expr(stmt.until_cond)
                self.emit(f"if {uc}: break")

            self.emit(f"{vname} += {t_step}")
            self.dedent()

        elif isinstance(stmt, ast.SelectStmt):
            if stmt.expr:
                sel_val = self.get_temp("_sel")
                self.emit(f"{sel_val} = {self.gen_expr(stmt.expr)}")
                first = True
                for conditions, stmts in stmt.when_clauses:
                    checks = [f"({sel_val} == {self.gen_expr(c)})" for c in conditions]
                    check_str = " or ".join(checks)
                    kw = "if" if first else "elif"
                    first = False
                    self.emit(f"{kw} {check_str}:")
                    self.indent()
                    if stmts:
                        for s in stmts: self.gen_stmt(s)
                    else:
                        self.emit("pass")
                    self.dedent()
                if stmt.otherwise_branch:
                    self.emit("else:")
                    self.indent()
                    for s in stmt.otherwise_branch: self.gen_stmt(s)
                    self.dedent()
            else:
                first = True
                for conditions, stmts in stmt.when_clauses:
                    checks = [f"({self.gen_expr(c)})" for c in conditions]
                    check_str = " or ".join(checks)
                    kw = "if" if first else "elif"
                    first = False
                    self.emit(f"{kw} {check_str}:")
                    self.indent()
                    if stmts:
                        for s in stmts: self.gen_stmt(s)
                    else:
                        self.emit("pass")
                    self.dedent()
                if stmt.otherwise_branch:
                    self.emit("else:")
                    self.indent()
                    for s in stmt.otherwise_branch: self.gen_stmt(s)
                    self.dedent()

        elif isinstance(stmt, ast.CallStmt):
            func = pli_name(stmt.callee)
            args = [self.gen_expr(a) for a in stmt.args]
            self.emit(f"{func}({', '.join(args)})")

        elif isinstance(stmt, ast.ReturnStmt):
            if stmt.value:
                val = self.gen_expr(stmt.value)
                self.emit(f"return {val}")
            else:
                self.emit("return")

        elif isinstance(stmt, ast.StopStmt):
            self.emit("sys.exit(0)")

        elif isinstance(stmt, ast.PutStmt):
            items_str = "[" + ", ".join(self.gen_expr(it) for it in stmt.items) + "]"
            skip_bool = "True" if stmt.skip else "False"
            skip_count_str = self.gen_expr(stmt.skip_count) if stmt.skip_count else "1"
            if stmt.formats:
                formats_repr = repr(stmt.formats)
                self.emit(f"_pli_put_edit({items_str}, {formats_repr}, skip={skip_bool}, skip_count={skip_count_str})")
            else:
                self.emit(f"_pli_put_list({items_str}, skip={skip_bool}, skip_count={skip_count_str})")

        elif isinstance(stmt, ast.GetStmt):
            var_names = []
            for item in stmt.items:
                if isinstance(item, ast.VarExpr):
                    var_names.append(pli_name(item.name))
                elif isinstance(item, ast.CallOrIndexExpr):
                    indices = [self.gen_expr(arg) for arg in item.args]
                    arr_name = pli_name(item.callee)
                    if len(indices) == 1:
                        var_names.append(f"{arr_name}[{indices[0]}]")
                    else:
                        var_names.append(f"{arr_name}[({', '.join(indices)})]")
            vars_joined = ", ".join(var_names)
            dummies = ", ".join(["None"] * len(var_names))
            self.emit(f"{vars_joined} = _pli_get_list({dummies})")

        elif isinstance(stmt, ast.ProcedureDecl):
            self.gen_procedure(stmt)

    def gen_expr(self, expr: ast.Expr) -> str:
        if isinstance(expr, ast.LiteralExpr):
            if expr.lit_type == 'STRING':
                return repr(expr.value)
            elif expr.lit_type == 'BIT':
                return repr(expr.value)
            else:
                return str(expr.value)

        elif isinstance(expr, ast.VarExpr):
            return pli_name(expr.name)

        elif isinstance(expr, ast.UnaryExpr):
            operand = self.gen_expr(expr.expr)
            if expr.op in ('^', '~', '!'):
                return f"(not ({operand}))"
            return f"({expr.op}{operand})"

        elif isinstance(expr, ast.BinaryExpr):
            left = self.gen_expr(expr.left)
            right = self.gen_expr(expr.right)
            if expr.op == '||':
                return f"_pli_concat({left}, {right})"
            elif expr.op == '=':
                return f"({left} == {right})"
            elif expr.op in ('^=', '\\=', '!='):
                return f"({left} != {right})"
            elif expr.op == '&':
                return f"({left} and {right})"
            elif expr.op == '|':
                return f"({left} or {right})"
            elif expr.op == '/':
                return f"({left} / {right})"
            elif expr.op == '**':
                return f"({left} ** {right})"
            else:
                return f"({left} {expr.op} {right})"

        elif isinstance(expr, ast.CallOrIndexExpr):
            callee_name = expr.callee.upper()
            args = [self.gen_expr(a) for a in expr.args]
            if callee_name in BUILTINS:
                func_name = BUILTINS[callee_name]
                return f"{func_name}({', '.join(args)})"
            else:
                target = pli_name(expr.callee)
                return f"_pli_call_or_index({target}, {', '.join(args)})"

        elif isinstance(expr, ast.SubstrExpr):
            target = self.gen_expr(expr.target)
            start = self.gen_expr(expr.start)
            length = self.gen_expr(expr.length) if expr.length else "None"
            return f"_pli_substr({target}, {start}, {length})"

        return "None"
